# fly.toml app configuration file generated for scroll-ai on 2023-07-16T13:06:13+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "scroll-ai"
primary_region = "mad"

[http_service]
  internal_port = 5005
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
